spring:
  security:
    oauth2:
      client:
        registration:
          SANDBOX:
            base-uri: ${BASE_URL}
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/sandbox
            scope: aisp, cbpii, pisp
            response_type: code
        provider:
          SANDBOX:
            authorization-uri: ${BASE_URL}/signin
            token-uri: ${BASE_URL}/token
